spring.datasource.url = jdbc:postgresql://localhost:5432/romitan
spring.datasource.username = postgres
spring.datasource.password = asil
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8080

#spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username = postgres
#spring.datasource.password = Akow8434
#spring.datasource.driver-class-name = org.postgresql.Driver
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto = update
#spring.servlet.multipart.max-file-size=300MB
#spring.servlet.multipart.max-request-size=300MB
#server.port=8080
